-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."country_law_column_reactions" add column "law_revision_id" uuid
--  not null;
