-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."law_revisions" add column "api_law_revision_id" text
--  not null;
