-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."world_histories" add column "official_launguage" integer
--  not null default '0';
