FROM hasura/graphql-engine:v2.34.0.cli-migrations-v3

# Dockerfileに渡す変数
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_HOST
ARG POSTGRES_PORT
ARG POSTGRES_DB
ARG HASURA_GRAPHQL_ADMIN_SECRET
ARG HASURA_GRAPHQL_JWT_SECRET
ARG HASURA_GRAPHQL_UNAUTHORIZED_ROLE

# # migration, metadataをコピー
COPY ./migrations /hasura_migrations
COPY ./metadata /hasura_metadata


# Hasura環境変数値設定
ENV HASURA_GRAPHQL_DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
ENV HASURA_GRAPHQL_ENABLE_CONSOLE="true"
ENV HASURA_GRAPHQL_ADMIN_SECRET="${HASURA_GRAPHQL_ADMIN_SECRET}"
ENV HASURA_GRAPHQL_JWT_SECRET="${HASURA_GRAPHQL_JWT_SECRET}"
ENV HASURA_GRAPHQL_UNAUTHORIZED_ROLE="${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}"

ENV HASURA_GRAPHQL_MIGRATIONS_DIR=/hasura_migrations
ENV HASURA_GRAPHQL_METADATA_DIR=/hasura_metadata

# 通信用ポート開放 8000
EXPOSE 8080
