-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE INDEX idx_law_revisions_law_id_created_at ON law_revisions (law_id, created_at DESC);
