-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."comments" add column "law_revision_column_column_id" text
--  null;
