-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."reactions" add column "official_gazette_column_id" UUID
--  null;
