-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."law_revision_columns" add column "column_id" text
--  not null unique;
