-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."house_of_councilors_histories" add column "diet_id" uuid
--  not null;
